name: tools_ui
description: A sample command-line application.
version: 1.0.0+1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  image: ^2.1.18
  cupertino_icons: ^1.0.0
  searchable_dropdown: ^1.1.3
  flutter_hooks: ^0.14.1
  hooks_riverpod: ^0.11.2
  shared_preferences: '>=0.5.12+2 <2.0.0'
  url_launcher: ^5.7.8
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 5b3b930da18244ecf2a7140a0e33a9892273797c
  tools:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  test: ^1.15.3

flutter:
  uses-material-design: true